### PR TITLE
add exp.test and required plotting util

### PR DESCRIPTION
**Pull request by nsteinme**
hey @dendritic, the old PR with exp.test was left hanging (by me) with unresolved merge conflicts - this is a new one without any conflicts. People wanted to use exp.test, and this just adds it, so let's please merge! Thanks -

### CODE REVIEW

**Comment by dendritic** [comment]
hey weren't we going to pull the exp package etc out into rigbox?

**Comment by nsteinme** [comment]
Yes, and it all is, except exp.test which is very useful for anyone doing
signals. We could rename exp.test to something else if you don't like it
having that name? Or what is the objection?

**Comment by dendritic** [comment]
Ok that's a good point. Perhaps the vis package is the sensible place for this then?

**Comment by nsteinme** [comment]
Hm, but the point of this is not to test visual stimuli (for which, in fact, it seems there is already a +vis/test.m) but to test any signals experiments, which could omit visual stimuli altogether. What about just in the signals root, called "expTest" or "testingGUI" or "sandbox" or something? Anyway, that is just my thought - if you like it in +vis I can put it there, just suggest a different name please!

**Comment by dendritic** [comment]
OK you've convinced me. Makes sense to keep it exp and it then meshes with rigbox nicely

**Pull request merged**
